repos:
  - hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
  - hooks:
      - id: prettier
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
  - hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
