name: Release builds

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  release-builds:
    name: Build ${{ matrix.target }}
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jty-converter
          archive: $bin-$tag-$target
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          profile: release
          checksum: sha512
