name: Release builds

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
      - name: Updated CHANGELOG.md
        env:
          GH_TOKEN: ${{ github.token }}
          FILE_TO_COMMIT: CHANGELOG.md
          DESTINATION_BRANCH: main
          MESSAGE: "chore(release): prepare for upcoming release (CHANGELOG.md)"
        run: |
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md

  release-builds:
    name: Build ${{ matrix.target }}
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: jty-converter
          archive: $bin-$tag-$target
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          profile: release
          checksum: sha512
